version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    network_mode: 'host'
  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    network_mode: 'host'
  event-bus:
    build:
      context: ./event-bus
      dockerfile: Dockerfile
    ports:
      - '4003:4003'
    network_mode: 'host'
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    network_mode: 'host'
