apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ms-ecommerce_shop-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: ms-ecommerce_cart-service
      context: cart-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/*.js'
            dest: .
    - image: ms-ecommerce_order-service
      context: order-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/*.js'
            dest: .
    - image: ms-ecommerce_event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/*.js'
            dest: .
